# Site settings
title: HKKKD's Blog
email: kaidi.he@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Click About to see the CV page.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hkkkd.github.com" # the base hostname & protocol for your site

disqus_shortname: hkkkd.disqus.com

github_username:  HKKKD

# Build settings
pygment: true
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks